name: Build meilisearch for Japanese

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Build MeiliSearch
        run: |
          git clone https://github.com/meilisearch/meilisearch
          cd meilisearch
          git checkout $GITHUB_REF_NAME
          cargo build --release -p meilisearch -p meilitool \
            --no-default-features \
            --features "analytics mini-dashboard japanese"

      - name: Archive MeiliSearch
        uses: actions/upload-artifact@v4
        with:
          name: meilisearch
          path: |
            meilisearch/release/meilisearch
            meilisearch/release/meilitool

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            meilisearch/release/meilisearch
            meilisearch/release/meilitool
